import 'package:flutter/material.dart';
import 'dart:developer' as developer;

class CarLogoHelper {
  static const Map<String, String> _brandAliases = {
    'mercedes': 'mercedes-benz',
    'mercedesbenz': 'mercedes-benz',
    'vw': 'volkswagen',
    'chevy': 'chevrolet',
    'landrover': 'land-rover',
    'rangerover': 'land-rover',
    'rollsroyce': 'rolls-royce',
    'alfaromeo': 'alfa-romeo',
    'astonmartin': 'aston-martin',
    'gmc': 'gmc',
  };

  /// Set of all available logo files in assets/logos/optimized/ (without .png)
  static const Set<String> _availableLogos = {
    '9ff',
    'abadal',
    'abarth',
    'abbott-detroit',
    'abt',
    'ac',
    'acura',
    'aiways',
    'aixam',
    'alfa-romeo',
    'alpina',
    'alpine',
    'alta',
    'alvis',
    'amc',
    'apollo',
    'arash',
    'arcfox',
    'ariel',
    'aro',
    'arrinera',
    'arrival',
    'artega',
    'ascari',
    'askam',
    'aspark',
    'aston-martin',
    'atalanta',
    'auburn',
    'audi-sport',
    'audi',
    'austin',
    'autobacs',
    'autobianchi',
    'axon',
    'bac',
    'baic-motor',
    'baojun',
    'beiben',
    'bentley',
    'berkeley',
    'berliet',
    'bertone',
    'bestune',
    'bharatbenz',
    'bitter',
    'bizzarrini',
    'bmw-m',
    'bmw',
    'borgward',
    'bowler',
    'brabus',
    'brammo',
    'brilliance',
    'bristol',
    'brooke',
    'bufori',
    'bugatti',
    'buick',
    'byd',
    'byton',
    'cadillac',
    'camc',
    'canoo',
    'caparo',
    'carlsson',
    'caterham',
    'changan',
    'changfeng',
    'chery',
    'chevrolet-corvette',
    'chevrolet',
    'chrysler',
    'cisitalia',
    'citroen',
    'cizeta',
    'cole',
    'corre-la-licorne',
    'cupra',
    'dacia',
    'daewoo',
    'daf',
    'daihatsu',
    'daimler',
    'dartz',
    'datsun',
    'david-brown',
    'dayun',
    'de-tomaso',
    'delage',
    'desoto',
    'detroit-electric',
    'devel-sixteen',
    'diatto',
    'dina',
    'dkw',
    'dmc',
    'dodge-viper',
    'dodge',
    'dongfeng',
    'donkervoort',
    'drako',
    'ds',
    'duesenberg',
    'eagle',
    'edag',
    'edsel',
    'eicher',
    'elemental',
    'elfin',
    'elva',
    'englon',
    'erf',
    'eterniti',
    'exeed',
    'facel-vega',
    'faraday-future',
    'faw-jiefang',
    'faw',
    'ferrari',
    'fiat',
    'fioravanti',
    'fisker',
    'foden',
    'force-motors',
    'ford-mustang',
    'ford',
    'foton',
    'fpv',
    'franklin',
    'freightliner',
    'fso',
    'gac-group',
    'gardner-douglas',
    'gaz',
    'geely',
    'general-motors',
    'genesis',
    'geo',
    'geometry',
    'gilbern',
    'gillet',
    'ginetta',
    'gmc',
    'golden-dragon',
    'gonow',
    'great-wall',
    'grinnall',
    'gumpert',
    'hafei',
    'haima',
    'haval',
    'hawtai',
    'hennessey',
    'higer',
    'hillman',
    'hindustan-motors',
    'hino',
    'hiphi',
    'hispano-suiza',
    'holden',
    'hommell',
    'honda',
    'hongqi',
    'hongyan',
    'horch',
    'hsv',
    'hudson',
    'hummer',
    'hupmobile',
    'hyundai',
    'ic-bus',
    'ih',
    'ikco',
    'infiniti',
    'innocenti',
    'intermeccanica',
    'international',
    'irizar',
    'isdera',
    'iso',
    'isuzu',
    'iveco',
    'jac',
    'jaguar',
    'jawa',
    'jba-motors',
    'jeep',
    'jensen',
    'jetour',
    'jetta',
    'jmc',
    'kaiser',
    'kamaz',
    'karlmann-king',
    'karma',
    'keating',
    'kenworth',
    'kia',
    'king-long',
    'koenigsegg',
    'ktm',
    'lada',
    'lagonda',
    'lamborghini',
    'lancia',
    'land-rover',
    'landwind',
    'laraki',
    'leapmotor',
    'levc',
    'lexus',
    'leyland',
    'li-auto',
    'lifan',
    'ligier',
    'lincoln',
    'lister',
    'lloyd',
    'lobini',
    'lordstown',
    'lotus',
    'lucid',
    'luxgen',
    'lynk-and-co',
    'mack',
    'mahindra',
    'man',
    'mansory',
    'marcos',
    'marlin',
    'maserati',
    'mastretta',
    'maxus',
    'maybach',
    'maz',
    'mazda',
    'mazzanti',
    'mclaren',
    'melkus',
    'mercedes-amg',
    'mercedes-benz',
    'mercury',
    'merkur',
    'mev',
    'mg',
    'microcar',
    'mini',
    'mitsubishi',
    'mitsuoka',
    'mk',
    'morgan',
    'morris',
    'mosler',
    'navistar',
    'nevs',
    'nikola',
    'nio',
    'nissan-gt-r',
    'nissan-nismo',
    'nissan',
    'noble',
    'oldsmobile',
    'oltcit',
    'omoda',
    'opel',
    'osca',
    'paccar',
    'packard',
    'pagani',
    'panhard',
    'panoz',
    'pegaso',
    'perodua',
    'peterbilt',
    'peugeot',
    'pgo',
    'pierce-arrow',
    'pininfarina',
    'plymouth',
    'polestar',
    'pontiac',
    'porsche',
    'praga',
    'premier',
    'prodrive',
    'proton',
    'qoros',
    'radical',
    'ram',
    'rambler',
    'ranz',
    'renault-samsung',
    'renault',
    'rezvani',
    'riley',
    'rimac',
    'rinspeed',
    'rivian',
    'roewe',
    'rolls-royce',
    'ronart',
    'rossion',
    'rover',
    'ruf',
    'saab',
    'saic-motor',
    'saipa',
    'saleen',
    'saturn',
    'scania',
    'scion',
    'seat',
    'setra',
    'sev',
    'shacman',
    'simca',
    'singer',
    'singulato',
    'sinotruk',
    'sisu',
    'skoda',
    'smart',
    'soueast',
    'spania-gta',
    'spirra',
    'spyker',
    'ssangyong',
    'ssc',
    'sterling',
    'studebaker',
    'stutz',
    'subaru',
    'suffolk',
    'suzuki',
    'talbot',
    'tata',
    'tatra',
    'tauro',
    'techart',
    'tesla',
    'toyota-alphard',
    'toyota-century',
    'toyota-crown',
    'toyota',
    'tramontana',
    'trion',
    'triumph',
    'troller',
    'tucker',
    'tvr',
    'uaz',
    'ud',
    'ultima',
    'vandenbrink',
    'vauxhall',
    'vector',
    'vencer',
    'venturi',
    'venucia',
    'vinfast',
    'vlf',
    'volkswagen',
    'volvo',
    'w-motors',
    'wanderer',
    'wartburg',
    'weltmeister',
    'western-star',
    'westfield',
    'wey',
    'wiesmann',
    'willys-overland',
    'workhorse',
    'wuling',
    'xpeng',
    'yulon',
    'yutong',
    'zarooq-motors',
    'zastava',
    'zaz',
    'zeekr',
    'zenos',
    'zenvo',
    'zhongtong',
    'zinoro',
    'zotye',
  };

  /// Получить виджет логотипа по марке автомобиля
  static Widget getLogoWidget(
    BuildContext context,
    String make, {
    double size = 40,
  }) {
    final normalizedMake = make.toLowerCase().trim().replaceAll(' ', '');

    developer.log(
      'CarLogoHelper: looking for="$normalizedMake"',
      name: 'CarLogoHelper',
    );

    // Get the base file name
    final fileName = _brandAliases[normalizedMake] ?? normalizedMake;

    // Check if the logo actually exists in our assets pool to avoid load errors
    if (_availableLogos.contains(fileName)) {
      final isDark = Theme.of(context).brightness == Brightness.dark;

      final logoImage = Image.asset(
        'assets/logos/optimized/$fileName.png',
        width: size * 0.75,
        height: size * 0.75,
        fit: BoxFit.contain,
        errorBuilder: (context, error, stackTrace) {
          developer.log('Logo error for "$fileName"', name: 'CarLogoHelper');
          return Icon(Icons.directions_car_rounded, size: size * 0.8);
        },
      );

      // In dark mode, logos (often dark PNGs) need a white bg to be visible
      if (isDark) {
        return Container(
          width: size,
          height: size,
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(size * 0.2),
          ),
          padding: EdgeInsets.all(size * 0.1),
          child: Center(child: logoImage),
        );
      }

      return Transform.scale(scale: 1.6, child: logoImage);
    } else {
      // Fallback
      return Icon(Icons.directions_car_rounded, size: size * 0.8);
    }
  }
}
